### ISSUE TITLE
[Docs] Was image created by mermaid?

### ISSUE THREAD

**Issue by Fxplorer** [CSBiology/BioFSharp#135]
![](https://i.imgur.com/LXBvhmi.png)

I am curious if the [image](https://i.imgur.com/LXBvhmi.png) used in docs/index.fsx was originally created in mermaid or what tool was used?

**Comment by kMutagene** [comment]
Hi @Fxplorer, no i created that image in PowerPoint actually :D I am sure you can create something similar with mermaid (i would most likely use mermaid for something like this these days as well), but getting the layout like this could be tricky, maybe a modified [block diagram](https://mermaid.js.org/syntax/block.html)?
