### ISSUE TITLE
Should FSharp.Care and FSharp.Stats be added as submodules?

### ISSUE THREAD

**Issue by benjaminsaljooghi** [CSBiology/BioFSharp#23]
Should FSharp.Care and FSharp.Stats be added as [submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules)? This would make it more convenient to build this repository after cloning it.

**Comment by HLWeil** [comment]
FSharp.Care and FSharp.Stats are standalone repositories and are intended to be kept that way. 
The way they are integrated in BioFSharp (and not as nuget packages) is meant to make it easier for people to develope on Biofsharp and those projects simultaneously. This comes of course with the cost of more manual cloning, pulling and pushing. But after all, downloading those repositories is meant to be done by contributors.

For users, there is a repository containing the pre compiled libraries. It is called **CsbScaffold** and is updated with the new .dll-files regularly.

**Comment by kMutagene** [comment]
Its been a long time, but we decided to go the route of serving nuget packages [FSharpAux](https://github.com/CSBiology/FSharpAux/tree/nuget) and [FSharp.Stats](https://github.com/CSBiology/FSharp.Stats/tree/nuget) on nuget branches via git.

See a4085bdc150477319e2f32462b0e9b1613caebe5 

It is further planned to release these packages on nuget directly, but there is currently to much going on in those repositories.
