### ISSUE TITLE
Cannot run NUnit tests from Visual Studio

### ISSUE THREAD

**Issue by benjaminsaljooghi** [CSBiology/BioFSharp#24]
FAKE will execute the tests via the NUnit.Runners nunit-console.exe but Visual Studio won't pick up tests? I've tried referencing all the NUnit paket dll's to no avail.

**Comment by HLWeil** [comment]
I'm not quite sure if I got you correctly. 
Running tests via NUnit is not part of the standard build process in VS. As you said, it is initialised by the FAKE tools. Those are called when running the **build.cmd**. For me it looks like this: 
[
![capture](https://user-images.githubusercontent.com/17880410/33960973-dc09f5cc-e065-11e7-94a9-1b090cb780cc.PNG)
](url)
I hope I did not completely miss your point. If so, then let me know.

**Comment by benjaminsaljooghi** [comment]
You can run NUnit tests from Visual Studio via `Test -> Run -> All Tests`

![image](https://user-images.githubusercontent.com/15173618/33972660-ba27aafc-e0ca-11e7-9d8b-7877c56c56dc.png)

[This requires an installation of the NUnit test adapter.](https://stackoverflow.com/questions/43007761/how-to-run-nunit-tests-in-visual-studio-2017) If you install this via NuGet you can run the single toy test in `BioFSharp.Tests`. Then if you open `Test -> Windows -> Test Explorer` you can see the results, it should just be the one passing `hello returns 42` test. I was able to do this on my PC at home, but can't get it to work on my laptop right now. The issue I raise here is that, ideally, this should just work after executing `build.cmd` without having to configure NuGet packages etc.

**Comment by benjaminsaljooghi** [comment]
And as for your EDIT, I originally intended that project to be a test suite but then decided to change it to just a console application because then the FAKE target `run tests` would fail if Alea were not installed.

**Comment by kMutagene** [comment]
This issue is quite old and the project structure changed quite a lot, feel free to reopen this if needed.
