### ISSUE TITLE
[BUG] Fasta reader cant read from gzip file

### ISSUE THREAD

**Issue by kMutagene** [CSBiology/BioFSharp#36]
**Describe the bug**
Trying to read a fasta file from a gzip archive results in an error

**To Reproduce**
1. Open `BioFSharp.IO`
2. Use `FastA.fromGzipFile` to read docsrc/content/Chalmy_Cp.fasta.gz

**Expected behavior**
A sequence of FastaItems is created 

**Screenshots**
![image](https://user-images.githubusercontent.com/21338071/50540270-1dd15e00-0b8f-11e9-9a72-9d811d52a01d.png)

**OS and framework information (please complete the following information):**
 - OS: Windows 10
 - OS 1809
 - .Net core SDK version : 2.1.500

**Additional context**
The function uses the `readFileGZip` function from FSharpAux.IO. The relevant code is:

    /// Reads a gZip file line by line without creating a tempory file
    /// Alternatively use FileEnumerator
    let readFileGZip (filePath:string) =
        seq {use reader     = File.OpenRead(filePath)
             use unzip      = new GZipStream(reader, CompressionMode.Decompress, true)
             unzip.Seek(0L,SeekOrigin.Begin) |> ignore
             use textReader = new StreamReader(unzip, Encoding.Default)
             while not textReader.EndOfStream do
                yield textReader.ReadLine()}

**Comment by Joott** [comment]
[Fix decompression in readFileGZip #8](https://github.com/CSBiology/FSharpAux/pull/8) fixes the problem with the function. After an update `FastA.fromGzipFile` should work as expected.
