### ISSUE TITLE
FastA to GFF3 conversion

### ISSUE THREAD

**Issue by HLWeil** [CSBiology/BioFSharp#48]
### Description
 
Protein data analysis tools make use of information about the gene loci of the proteins in order to consider relation. This kind of information can nicely be stored in and read from a GFF3 file. 
Some Tools require a GFF3 file. To tackle this if you only have a FastA at hand. An automatic converter might be nice.

### Implementation Steps

- [x] Refurbish FastA Header parser

An old implementation which automatically parses UniProt style FastA header is present in BioFSharp.BioID. It needs to be refurbished.

- [x] add FastA to GFF3 parser

Given the info from the parsed FastA header this is just a small function getting the protein names from the header, grouping them by the gene loci and creating GFF3 items of them accordingly.

**Comment by HLWeil** [comment]
FastA Header parser Included in f2a16aaa2456b0c431f6d50d0f78a12834671e97

FastA to GFF3 parser Included in 2cdd3537398040e1508736bd734b22a67a7c46e7

**Comment by kMutagene** [comment]
@HLWeil , can this issue be closed? it seems like you have implemented the full feature

**Comment by HLWeil** [comment]
@kMutagene yes, I'll close it now.
