### ISSUE TITLE
Should 'release' build target require confirmation?

### ISSUE THREAD

**Issue by bvenn** [CSBiology/BioFSharp#49]
### Description

When writing documentation it is useful to have the following commands at hand:

`fake build -t releaselocal` for a local generation of the docs
`fake build -t releasedocs` for pushing the docs to gh-pages

When accidentally typing `fake build -t release local` or other variants, the `release` target is called and all comitted and uncommitted changes are pushed, thereby bumping the version and updating the nuget package.

It would be nice to have an additional security confirmation if `fake build -t release xxx` is entered
This affects all CSBiology projects.

**Comment by kMutagene** [comment]
Quick but most likely suboptimal fix implemented: b8516fd776476f22e82ceab2ac7b74cd20038b4c
Suboptimal because it throws an error if the confirmation is negative. Maybe there is a way to use the cancellation token of the targetContext, but i was not able to make that work.
