### ISSUE TITLE
[Feature Request] Documentation for Ontology Enrichment

### ISSUE THREAD

**Issue by Freymaurer** [CSBiology/BioFSharp#58]
**Is your feature request related to a problem? Please describe.**
I wanted to use the OntologyEnrichment module but there is close to no documentation on how to use it. 

**Describe the solution you'd like**
Replace the filler documentation [here](https://csbiology.github.io/BioFSharp/GESA.html) with an actual documentation.

**Comment by bvenn** [comment]
closed by d5527aba3d1282170895af0b3939c7e58bbfcf05
