### ISSUE TITLE
[Docs] Clarify Nucleotides.inverse function

### ISSUE THREAD

**Issue by rolfsuter** [CSBiology/BioFSharp#65]
**BioFSharp.Nucleotides.inverse**
The `inverse` function in the [BioFSharp.Nucleotides](https://github.com/CSBiology/BioFSharp/blob/master/src/BioFSharp/Nucleotides.fs) module needs clarification. It is unclear what "inversion" means on the nucleotide level of a nucleotide sequence. 

The given example states, that the sequence "ATGC" is converted to "CGTA". This is usually understood as reading the string from the back and thus reversing the nucleotide sequence. Reversing the nucleotide sequence cannot be done on the nucleotide level.

Please give a reference with the biological relevance and explanation of the conversion performed by this function.

**Comment by ZimmerD** [comment]
Hi @rolfsuter,
 
Thank you for reporting this. I agree that this function name is not fitting the conventions. We will change the name in in the next release to 'reverse'. 

Regarding the biological relevance, we will include an code example which shows how the function 'complement' and this function can be combined to produce the reverse complement of a sequence.

Cheers
David

**Comment by rolfsuter** [comment]
Hi David

Thank you for your reply. I assume that this function `reverse` needs to be completely refactored since such a function is expected to work on a sequence of nucleotides and not on a nucleotide itself. Please see also #66. 

Cheers
Rolf

**Comment by muehlhaus** [comment]
See #66
