### ISSUE TITLE
[BUG] Nucleotides.antiparallel delivers unexpected results

### ISSUE THREAD

**Issue by rolfsuter** [CSBiology/BioFSharp#66]
**Describe the bug**
The `antiparallel` function in the [BioFSharp.Nucleotides](https://github.com/CSBiology/BioFSharp/blob/master/src/BioFSharp/Nucleotides.fs) module delivers unexpected results. It works on single nucleotides instead of a nucleotide sequence.

**To Reproduce**
- I did not actually test it.
- I checked the source code only.

**Expected behavior**
I expect the `antiparallel` function to deliver the sequence of a complementary DNA strand in 5' to 3' direction. 

A double stranded DNA:
`5'-GAAATGTTCTTGCAGTTAA-3'`
`3'-CTTTACAAGAACGTCAATT-5'`

The sense strand with the original sequence is the upper strand in this schema. The antiparallel DNA strand is the lower strand.  The sequence of the antiparallel DNA strand (reverse-complement) in 5' to 3' direction is:
`5'-TTAACTGCAAGAACATTTC-3'`

The function is expected to work on a sequence of nucleotides, e.g. `Nucleotide list`. The algorithm would look like:
`myDnaSequence |> List.map (fun nuc -> Nucleotides.complement nuc)  |> List.rev`

For a simple online tool see:
[https://www.bioinformatics.org/sms/rev_comp.html](https://www.bioinformatics.org/sms/rev_comp.html)

**Suggestion**
- Remove `Nucleotides.antiparallel` function
- (Remove the  `Nucleotides.inverse` function. Compare with #65)
- Create a module for manipulating nucleotide sequences with functions:
  - `reverse: Nucleotide list -> Nucleotide list`
  - `complement: Nucleotide list -> Nucleotide list`
  - `reverseComplement: Nucleotide list -> Nucleotide list`
Where list could (also) be BioList, BioSeq, BioArray.

**Comment by muehlhaus** [comment]
Hi @rolfsuter,

thank you for reporting this issue. You are absolutely right. We included your suggestion into the repro, and it will be part in the next release coming soon.

All the best,
Timo

**Comment by rolfsuter** [comment]
@muehlhaus 
Hi Timo!

That's great.

All the best
Rolf

**Comment by bvenn** [comment]
closed by 27ab68f84aacd6de01a194dc5542da90a85e59d4
Documentation can be seen [here](https://csbiology.github.io/BioFSharp/BioCollections.html).
