### ISSUE TITLE
[Feature Request] Increase verbosity of Sailent.compute

### ISSUE THREAD

**Issue by ZimmerD** [CSBiology/BioFSharp#74]
**Is your feature request related to a problem? Please describe.**
I really like Sailent. Since it can take a while to compute, I would like a verbose option that tracks the bootstrapping loop so one can infer how much time it will take to run.

**Comment by kMutagene** [comment]
👌 💯

**Comment by ZimmerD** [comment]
Thank you for increasing the verbosity! But I think i you might have overdriven UwU. In case of curiosity this is the result that is now given:

![](https://media.giphy.com/media/hvLRBGxVyfdzUhRbN1/giphy.gif)

**Comment by kMutagene** [comment]
i had another go in 4e9a935d013760203b84fb79e50665f9cfe81d7a , give it a try and tell me if its to ur liking :3

**Comment by kMutagene** [comment]
@ZimmerD can thsi be closed?

**Comment by kMutagene** [comment]
closed due to lack of more memes.
