### ISSUE TITLE
[Feature Request] Optimize Sailent to increase computation speed

### ISSUE THREAD

**Issue by kMutagene** [CSBiology/BioFSharp#75]
**Is your feature request related to a problem? Please describe.**
Sailent is pretty slow, as it samples bootstrap distributions millions of times depending on the iteration count. The current implementation uses an array shuffle function and takes the first n entries after creation of the shuffled array. This can be greatly improved upon.

**Comment by kMutagene** [comment]
bootstrapping is now way faster with 844d2efcdd4b85c9e1c80f0160fb74e72f514a90

**Comment by HLWeil** [comment]
I think the computation speed of the initial data characterization step can be further optimized.

**Comment by HLWeil** [comment]
With PR #82, it's possible to work through datasets of millions of items in minutes, so I think we can close this issue again, right @kMutagene?
