### ISSUE TITLE
[BUG]OBO parser skips all relationships but the last

### ISSUE THREAD

**Issue by kMutagene** [CSBiology/BioFSharp#93]
**Describe the bug**
the OBO type seems to have some differences from the specification

**To Reproduce**
Parse this file: http://www.obofoundry.org/ontology/ms.html

**Expected behavior**
Here is an example:

[Term]
id: MS:1000014
name: accuracy
def: "Accuracy is the degree of conformity of a measured mass to its actual value." [PSI:MS]
xref: value-type:xsd\:float "The allowed value-type for this CV term."
is_a: MS:1000480 ! mass analyzer attribute
relationship: has_units MS:1000040 ! m/z
relationship: has_units UO:0000169

should contain both relationship lines.

Newest obo format specifications can be found here: https://owlcollab.github.io/oboformat/doc/GO.format.obo-1_4.html

**Comment by bvenn** [comment]
I think there was a similar issue for alt_ids in #35.

**Comment by kMutagene** [comment]
You are right, the specific error is an easy fix by changing the type from string to string list. Looking at the parser however showed some more issues i will fix to make it parse spec 1.4 correctly.

**Comment by kMutagene** [comment]
While 805f3fa fixes this issue and extends the term type to fit spec 1.4, there is a lot of work to be done to make the parser complete to the full specifications (we also need writers theoretically, but this is not a priority)
